apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data: 
  config.ini: |-
    [general]
    debug_mode=false
    host=0.0.0.0
    port=5000

    tls_enabled={{ .Values.tls.enabled }}
    cert_file={{ .Values.tls.cert_file }}

    ; Target Web server URL
    ui_url=http://ui:3000

    ; Target API server URL
    api_url=http://app:8000

    ; additional address to complete the authorization session
    additional_logout_path=/openid-connect-auth/logout

    ; Path to swagger (print on /token page)
    swagger_url=http://app:8000/swagger-ui/index.html

    ; The URL to which you should be redirected after authorization
    redirect_url=/token
    ;redirect_url=/home

    [keycloak]
    keycloak_url={{ .Values.keycloak.url }}
    protocol={{ .Values.keycloak.protocol }}
    realm={{ .Values.keycloak.realm }}
    client_id={{ .Values.keycloak.clientId }}
    client_secret={{ .Values.keycloak.clientSecret }}

    [log]
    dir=
    level=INFO