/*
 * User Service
 *
 * This is simple client API
 *
 * API version: 1.0.0
 * Contact: schetinnikov@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"net/http"

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"

	_ "otus/crud/docs"

	"github.com/prometheus/client_golang/prometheus/promhttp"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	router.Use(PrometheusMiddleware)

	// Swagger UI
	router.PathPrefix("/swagger-ui/").Handler(httpSwagger.WrapHandler)
	// Prometheus endpoint
	router.Path("/prometheus").Handler(promhttp.Handler())
	// Serving static files
	router.PathPrefix("/").Handler(http.FileServer(http.Dir("./static/")))

	// Сервис готов к работе
	isReady.Store(true)

	return router
}

var routes = Routes{
	// State handlers
	Route{"Health", "GET", "/health", Health},
	Route{"Ready", "GET", "/ready", Ready},
	// API handlers
	Route{"CreateUser", "POST", "/api/v1/users", CreateUser},
	Route{"DeleteUser", "DELETE", "/api/v1/users/{userId}", DeleteUser},
	Route{"FindUserById", "GET", "/api/v1/users/{userId}", FindUserById},
	Route{"UpdateUser", "PUT", "/api/v1/users/{userId}", UpdateUser},
}
