/*
 * User Service
 *
 * This is simple client API
 *
 * API version: 1.0.0
 * Contact: schetinnikov@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"flag"
	"log"
	"net/http"

	srv "otus/crud/internal"
	"otus/crud/internal/config"
	"otus/crud/internal/database"
)

// @title OTUS Homework #04
// @version 1.0
// @description CRUD User app
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1
// @schemes http
func main() {
	configPath := flag.String("config", "application.yaml", "Path to config file")
	flag.Parse()

	log.Printf("Loading configuration: %v", configPath)
	config.LoadConfig(*configPath)

	db, err := database.New()
	if err != nil {
		log.Fatal(err)
	}
	srv.SetDB(db.DB)

	log.Printf("Server started")

	router := srv.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
