/*
 * User Service
 *
 * This is simple client API
 *
 * API version: 1.0.0
 * Contact: schetinnikov@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	srv "otus/crud/internal"
)

func main() {
	log.Printf("Server started")

	router := srv.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
