services:
  app:
    env_file: .env
#    image: ${DOCKER_REGISTRY}/wsgi:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: "tail -f /dev/null"
    volumes:
      - ./config.ini:/app/config.ini
    ports:
      - "5000:5000"