apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  application.yaml: |-
    datasource:
        host: {{ .Values.global.postgresql.service.name | default "db-postgresql" }}
        port: {{ .Values.global.postgresql.service.ports.postgresql | default "5432" }}
        name: {{ .Values.global.postgresql.auth.database | default "users" }}
        # Логин и пароль подставятся из env-переменных!