apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USERNAME: {{ .Values.global.postgresql.auth.username | b64enc }}
  DB_PASSWORD: {{ .Values.global.postgresql.auth.password | b64enc }}