apiVersion: v1
kind: Service
metadata:
  name: {{ include "warehouse.fullname" . }}
  labels:
    {{- include "warehouse.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "warehouse.selectorLabels" . | nindent 4 }}
