basePath: /api/v1
definitions:
  swagger.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  swagger.StatusResponse:
    properties:
      status:
        type: string
    type: object
  swagger.User:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: CRUD User app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 'OTUS Homework #04'
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя в системе
      parameters:
      - description: Данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/swagger.User'
      produces:
      - application/json
      responses:
        "200":
          description: Успешно создан
          schema:
            $ref: '#/definitions/swagger.User'
        "400":
          description: Неверные входные данные
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
      summary: Создать нового пользователя
      tags:
      - Пользователи
  /users/{id}:
    delete:
      description: Удаляет пользователя по его идентификатору
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешно удален
          schema:
            $ref: '#/definitions/swagger.StatusResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
      summary: Удалить пользователя
      tags:
      - Пользователи
    get:
      description: Возвращает информацию о пользователе по его идентификатору
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешный запрос
          schema:
            $ref: '#/definitions/swagger.User'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
      summary: Найти пользователя по ID
      tags:
      - Пользователи
    put:
      consumes:
      - application/json
      description: Обновляет информацию о пользователе
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      - description: Обновленные данные пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/swagger.User'
      produces:
      - application/json
      responses:
        "200":
          description: Успешно обновлен
          schema:
            $ref: '#/definitions/swagger.User'
        "400":
          description: Неверные входные данные
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/swagger.ErrorResponse'
      summary: Обновить данные пользователя
      tags:
      - Пользователи
schemes:
- http
swagger: "2.0"
