apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data: 
  config.ini: |-
    [GENERAL]
    debug = False
    host = 0.0.0.0
    port = 5000

    ui_url = http://ui:80
    default_service_url = http://app:8000
    additional_logout_path = /openid-connect-auth/logout
    redirect_url = /token

    [ROUTES]
    billing.prefix = billing
    billing.url = http://billing:8080/api/v1

    notification.prefix = notification
    notification.url = http://notification:8081/api/v1

    order.prefix = order
    order.url = http://order:8082/api/v1

    [KEYCLOAK]
    url = {{ .Values.keycloak.url }}
    protocol = {{ .Values.keycloak.protocol }}
    realm = {{ .Values.keycloak.realm }}
    client_id = {{ .Values.keycloak.clientId }}
    client_secret = {{ .Values.keycloak.clientSecret }}
    admin_username = {{ .Values.keycloak.adminUsername }}
    admin_password = {{ .Values.keycloak.adminPassword }}

    [SECURITY]
    use_ssl = {{ .Values.security.use_ssl }}
    cert_file = {{ .Values.security.cert_file }}
    token_expire_hours = {{ .Values.security.token_expire_hours | default 24 }}

    [LOGGING]
    level = DEBUG
    save_file = False
    dir = logs
    file = /var/log/api-gateway.log