{
 "title": "Kubernetes Application Resources",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Application Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "description": "Memory usage by application pods",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{namespace=\"otus\", pod=~\"app.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage by app pod",
   "type": "timeseries",
   "description": "CPU usage by application pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"otus\", pod=~\"app-.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage vs Limits",
   "type": "timeseries",
   "description": "Current memory usage vs requests and limits",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{namespace=\"otus\", pod=~\"app.*\"}) by (pod)",
     "legendFormat": "{{pod}} - Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"otus\", pod=~\"app.*\", resource=\"memory\"}) by (pod)",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}) by (pod)",
     "legendFormat": "Memory Request"
    }
   ]
  },
  {
   "title": "CPU Usage vs Limits",
   "type": "timeseries",
   "description": "Current CPU usage vs requests and limits",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(process_cpu_seconds_total{namespace=\"otus\", pod=~\"app.*\"}[1m])) / sum (machine_cpu_cores) * 100",
     "legendFormat": "App process CPU usage"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{namespace=\"otus\", pod=~\"app.*\"}[1m])) / sum (machine_cpu_cores) * 100",
     "legendFormat": "All process in container CPU usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"otus\", pod=~\"app.*\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "CPU Limit"
    }
   ]
  }
 ]
}